task_manager/task_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path(
        '',
        include('tasks.urls', namespace='tasks')
    ),
    path(
        'auth/',
        include('users.urls', namespace='users')
    ),
    path(
        'friends/',
        include('friends.urls', namespace='friends')
    ),
    path(
        'profile/',
        include('user_profile.urls', namespace='profile')
    ),
    path(
        'admin/',
        admin.site.urls
    )
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

task_manager/tasks/urls.py
from django.urls import path

from .views import add_task, main_page, task_detail

app_name = 'tasks'

urlpatterns = [
    path('', main_page, name='main_page'),
    path('add/', add_task, name='add_task'),
    path('task/<int:task_id>/', task_detail, name='task_detail'),
]

task_manager/users/urls.py
from django.urls import path

from .views import Login, Logout, SignUp


app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        Logout.as_view(),
        name='logout'
    ),
    path(
        'signup/',
        SignUp.as_view(),
        name='signup'
    ),
    path(
        'login/',
        Login.as_view(),
        name='login'
    ),
]

task_manager/tasks/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()
DEFAULT = 0
TASK_STATUS_CHOICES = [
    ('in_progress', 'Выполняется'),
    ('completed', 'Выполнено'),
    ('postponed', 'Отложено'),
    ('dropped', 'Брошено'),
    ('cancelled', 'Отменено')
]


class Task(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='owned_tasks'
    )
    contributors = models.ManyToManyField(
        User,
        related_name='participating_tasks',
        blank=True
    )
    name = models.CharField(
        max_length=64
    )
    description = models.TextField()
    status = models.CharField(
        choices=TASK_STATUS_CHOICES,
        default=TASK_STATUS_CHOICES[DEFAULT],
        max_length=16
    )
    date = models.DateField(
        auto_now_add=True
    )
    end_date = models.DateField(
        null=True,
        blank=True
    )

    def __str__(self):
        return self.name

    class Meta:
        indexes = [
            models.Index(fields=['status']),
            models.Index(fields=['end_date'])
        ]

task_manager/tasks/forms.py
from django import forms

from .models import Task, TASK_STATUS_CHOICES


class TaskForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(),
        label='Название таски'
    )
    description = forms.CharField(
        widget=forms.Textarea,
        label='Более подробное описание таски'
    )
    status = forms.ChoiceField(
        choices=TASK_STATUS_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control'}),
        label='Статус'
    )
    end_date = forms.DateField(
        required=False,
        widget=forms.DateInput(attrs={
            'type': 'date',
            'min': '1970-01-01'
        }),
        label="Дата дедлайна"
    )
    contributors = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={'rows': 1}),
        label="Укажите юзернеймы пользователей, "
              "с которыми будете вместе работать "
              "над этой таской (через пробел, без "
              "лишних разделительных символов)"
    )

    class Meta:
        model = Task
        fields = ['name', 'description', 'status', 'end_date',]

    def clean_contributors(self) -> list:
        info = self.cleaned_data['contributors']
        if info:
            return ''.join(info).split(' ')
        return []

task_manager/tasks/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from task_manager.settings import BASE_REDIRECT_URL

from .components import (
    add_contributors_to_task,
    filter_tasks_by_status,
    get_request_user_tasks,
    order_tasks_by_end_date,
    request_user_is_has_task_access,
    save_task_form
)
from .forms import TaskForm
from .models import Task


@login_required
def main_page(request):
    template = 'main_page.html'
    tasks = get_request_user_tasks(request)
    status = request.GET.get('status')
    tasks = filter_tasks_by_status(tasks, status)
    tasks = order_tasks_by_end_date(tasks)
    context = {
        'tasks': tasks,
        'status': status
    }
    return render(request, template, context)


@login_required
def add_task(request):
    template = 'add_task.html'
    form = TaskForm(request.POST or None)

    if form.is_valid():
        save_task_form(form, request)
        return redirect(BASE_REDIRECT_URL)

    context = {
        'form': form,
    }
    return render(request, template, context)


@login_required
def task_detail(request, task_id):
    template = 'task_detail.html'
    edit = request.GET.get('edit', False)
    task = get_object_or_404(Task, pk=task_id)

    if not request_user_is_has_task_access(request, task, edit):
        return render(request, 'access_denied.html')

    form = TaskForm(request.POST or None, instance=task)
    if form.is_valid():
        contributors_usernames = form.clean_contributors()
        add_contributors_to_task(task, contributors_usernames)
        return redirect('tasks:task_detail', task_id=task_id)

    context = {
        'form': form,
        'task': task,
        'edit': edit,
        'user': request.user
    }
    return render(request, template, context)

task_manager/templates/includes/footer.html
{% load static %}
<footer style="margin: 24px" class="border-top text-center py-3">
  <p style="font-weight:bold; font-size:18px">
    меня расщепилна атомы
  </p>
</footer>

task_manager/templates/includes/header.html
{% load static %}
<header style="background: #F3CBCE">
  <nav class="navbar navbar-light" style="font-weight:bold">
    <div class="container">
      <a class="navbar-brand" href="{% url 'tasks:main_page' %}?status=in_progress">
        <img src="{% static 'img/logo.png' %}" width="70" height="70" class="d-inline-block; vertical-align: middle" alt="">
        <span style="font-size:26px; font-family: monospace; vertical-align: middle; color: #AF7866"><b>TASKF#CKER</b></span>
      </a>
      <ul class="nav nav-pills">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link
               {% if request.resolver_match.view_name  == 'tasks:main_page' %}
                active
               {% endif %}
               "
               href="{% url 'tasks:main_page' %}?status=in_progress"
            >
              Ваши таски
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link
               {% if request.resolver_match.view_name  == 'tasks:add_task' %}
                active
               {% endif %}
               "
               href="{% url 'tasks:add_task' %}"
            >
              Новая таска
            </a>
          </li>
          <li class="nav-item">
            <form method="POST" action="{% url 'users:logout' %}" style="display:inline;">
              {% csrf_token %}
              <button class="btn btn-link nav-link link-light" style="background:none; border:none; cursor:pointer;">
                Выйти
              </button>
            </form>
          </li>
          <li>
            <a class="nav-link link-light"
               href=""
            >
              Профиль {{ request.user.username }}
            </a>
          </li>
        {% else %}
          {% if request.resolver_match.view_name == 'users:login' %}
            <li class="nav-item">
              <a class="nav-link link-light" href="{% url 'users:signup' %}">Еще нет аккауанта? Регистрация</a>
            </li>
          {% elif request.resolver_match.view_name == 'users:signup' %}
            <li class="nav-item">
              <a class="nav-link link-light" href="{% url 'users:login' %}">Уже зарегистированы? Войти</a>
            </li>
          {% else %}
            <li>
              <a class="nav-link link-light" href="{% url 'users:login' %}">Войти</a>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light" href="{% url 'users:signup' %}">Регистрация</a>
            </li>
          {% endif %}
        {% endif %}
      </ul>
    </div>
  </nav>
</header>

task_manager/templates/includes/task.html
{% load static %}
<div class="col">
    <a style="text-decoration: none" href="{% url 'tasks:task_detail' task.id %}">
    <div class="card text-center h-100">
        <div class="card-header bg-primary text-white"><b>{{ task.name }}</b></div>
        <div class="card-body">
            <p class="card-text">{{ task.description|truncatewords:20 }}</p>
        </div>
        <div class="card-footer">
            {% if task.end_date %}
                Выполнить к {{ task.end_date }}
            {% else %}
                Без дедлайна
            {% endif %}
            {% if not status %}
                <br>
                <b>{{ task.get_status_display }}</b>
            {% endif %}
        </div>
    </div>
    </a>
</div>