task_manager/task_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path(
        '',
        include('tasks.urls', namespace='tasks')
    ),
    path(
        'auth/',
        include('users.urls', namespace='users')
    ),
    path(
        'friends/',
        include('friends.urls', namespace='friends')
    ),
    path(
        'profile/',
        include('user_profile.urls', namespace='profile')
    ),
    path(
        'admin/',
        admin.site.urls
    )
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

task_manager/tasks/urls.py
from django.urls import path

from .views import add_task, main_page, task_detail

app_name = 'tasks'

urlpatterns = [
    path('', main_page, name='main_page'),
    path('add/', add_task, name='add_task'),
    path('task/<int:task_id>/', task_detail, name='task_detail'),
]

task_manager/user_profile/models.py
from django.db import models
from django.contrib.auth import get_user_model
from multiselectfield import MultiSelectField
from .choice_fields_options import (
    DEFAULT,
    LANGUAGES_CHOICES,
    PRIVACY_CHOICES
)

User = get_user_model()


class Profile(models.Model):
    owner = models.OneToOneField(
        User,
        on_delete=models.CASCADE
    )
    profile_picture = models.ImageField(
        upload_to='static/profile_pictures/',
        blank=True
    )
    bio = models.TextField(
        max_length=300,
        blank=True
    )
    languages = MultiSelectField(
        choices=LANGUAGES_CHOICES,
        max_length=300,
        blank=True
    )
    privacy = models.CharField(
        choices=PRIVACY_CHOICES,
        default=PRIVACY_CHOICES[DEFAULT],
        max_length=16
    )
    dark_theme = models.BooleanField(
        default=False
    )

    def __str__(self):
        return self.owner.__str__()


class SocialLinks(models.Model):
    profile = models.OneToOneField(
        Profile,
        on_delete=models.CASCADE
    )
    facebook_link = models.URLField(
        blank=True
    )
    twitter_link = models.URLField(
        blank=True
    )
    linkedin_link = models.URLField(
        blank=True
    )
    instagram_link = models.URLField(
        blank=True
    )
    youtube_link = models.URLField(
        blank=True
    )
    tiktok_link = models.URLField(
        blank=True
    )
    reddit_link = models.URLField(
        blank=True
    )
    telegram_link = models.URLField(
        blank=True
    )
    discord_link = models.URLField(
        blank=True
    )
    steam_link = models.URLField(
        blank=True
    )
    twitch_link = models.URLField(
        blank=True
    )

    def __str__(self):
        return self.profile.__str__()

task_manager/templates/profile/profile.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %}Ваши таски{% endblock title %}
{% block body %}
<div class="card shadow-sm p-4">
    <div class="row g-4">
        <div class="col-md-4 text-center">
            {% thumbnail profile_owner.profile.profile_picture "600x600" crop="center" upscale=True as pp %}
                <img class="card-img my-2" src="{{ pp.url }}">
            {% endthumbnail %}
            <h3 class="mt-3">{{ profile_owner.username }}</h3>
            <p class="text-muted">{{ profile_owner.first_name }} {{ profile_owner.last_name }}</p>
        </div>
        <div class="col-md-8">
            <h4>О себе</h4>
            <p>{{ profile_owner.profile.bio }}</p>

            <h4>Языки</h4>
            <p>{{ profile_owner.profile.get_languages_display }}</p>

            <h4>Приватность</h4>
            <p>{{ profile_owner.profile.get_privacy_display }}</p>

            <h4>Дополнительно</h4>
            <p>Тёмная тема: {% if profile_owner.profile.dark_theme %}Включена{% else %}Выключена{% endif %}</p>
        </div>
    </div>
</div>
{% endblock body %}