task_manager/task_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path(
        '',
        include('tasks.urls', namespace='tasks')
    ),
    path(
        'auth/',
        include('users.urls', namespace='users')
    ),
    path(
        'friends/',
        include('friends.urls', namespace='friends')
    ),
    path(
        'profile/',
        include('user_profile.urls', namespace='profile')
    ),
    path(
        'admin/',
        admin.site.urls
    )
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

task_manager/tasks/urls.py
from django.urls import path

from .views import add_task, main_page, task_detail

app_name = 'tasks'

urlpatterns = [
    path('', main_page, name='main_page'),
    path('add/', add_task, name='add_task'),
    path('task/<int:task_id>/', task_detail, name='task_detail'),
]

task_manager/users/urls.py
from django.urls import path

from .views import Login, Logout, SignUp


app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        Logout.as_view(),
        name='logout'
    ),
    path(
        'signup/',
        SignUp.as_view(),
        name='signup'
    ),
    path(
        'login/',
        Login.as_view(),
        name='login'
    ),
]

task_manager/tasks/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()
DEFAULT = 0
TASK_STATUS_CHOICES = [
    ('in_progress', 'Выполняется'),
    ('completed', 'Выполнено'),
    ('postponed', 'Отложено'),
    ('dropped', 'Брошено'),
    ('cancelled', 'Отменено')
]


class Task(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='owned_tasks'
    )
    contributors = models.ManyToManyField(
        User,
        related_name='participating_tasks',
        blank=True
    )
    name = models.CharField(
        max_length=64
    )
    description = models.TextField()
    status = models.CharField(
        choices=TASK_STATUS_CHOICES,
        default=TASK_STATUS_CHOICES[DEFAULT],
        max_length=16
    )
    date = models.DateField(
        auto_now_add=True
    )
    end_date = models.DateField(
        null=True,
        blank=True
    )

    def __str__(self):
        return self.name

    class Meta:
        indexes = [
            models.Index(fields=['status']),
            models.Index(fields=['end_date'])
        ]

task_manager/tasks/forms.py
from django import forms

from .models import Task, TASK_STATUS_CHOICES


class TaskForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(),
        label='Название таски'
    )
    description = forms.CharField(
        widget=forms.Textarea,
        label='Более подробное описание таски'
    )
    status = forms.ChoiceField(
        choices=TASK_STATUS_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control'}),
        label='Статус'
    )
    end_date = forms.DateField(
        required=False,
        widget=forms.DateInput(attrs={
            'type': 'date',
            'min': '1970-01-01'
        }),
        label="Дата дедлайна"
    )
    contributors = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={'rows': 1}),
        label="Укажите юзернеймы пользователей, "
              "с которыми будете вместе работать "
              "над этой таской (через пробел, без "
              "лишних разделительных символов)"
    )

    class Meta:
        model = Task
        fields = ['name', 'description', 'status', 'end_date',]

    def clean_contributors(self) -> list:
        info = self.cleaned_data['contributors']
        if info:
            return ''.join(info).split(' ')
        return []

task_manager/templates/access_denied.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Нет доступа
{% endblock title %}
{% block body %}
<div class="container text-center mt-5">
  <h1 class="display-4 text-danger">Доступ запрещен</h1>
  <p class="lead mt-3">Я тебя сюда не пущу. И он тебя сюда не пустит. Никто не пустит</p>
  <a href="{% url 'tasks:main_page' %}" class="btn btn-primary mt-4">К своим таскам</a>
</div>
{% endblock body %}

task_manager/templates/add_task.html
{% extends 'base.html' %}
{% load user_filters %}
{% block title %}
Новая таска
{% endblock %}
{% block body %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Новая таска
          </div>
          <div class="card-body">
            <form method="POST" action="{% url 'tasks:add_task' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group row my-3 p-3">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
              </label>
              {{ field|addclass:'form-control' }}
              {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                  {{ field.help_text|safe }}
                </small>
              {% endif %}
              </div>
            {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  Сохранить
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

task_manager/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image" href="{% static 'img/fav/fav.ico' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}">
    <title>
    {% block title %}
    {% endblock title %}
    </title>
  </head>
  <body style="background: #FEF7F1">
  {% include 'includes/header.html' %}
  <main>
      {% block body %}
      {% endblock body %}
  </main>
  {% include 'includes/footer.html' %}
  </body>
</html>

task_manager/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Ваши таски{% endblock title %}
{% block body %}
<nav class="navbar navbar-light" style="font-weight:bold; margin-top: 24px">
  <div class="container">
    <ul class="nav nav-pills">
      <li class="nav-item">
        <a class="nav-link
           {% if status == 'in_progress' %}
            active
           {% endif %}
           "
           href="?status=in_progress"
        >
            Активные
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link
           {% if status == 'postponed' %}
            active
           {% endif %}
           "
           href="?status=postponed"
        >
          Отложено
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link
           {% if status == 'completed' %}
            active
           {% endif %}
           "
           href="?status=completed"
        >
          Выполнено
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link
           {% if status == 'dropped' %}
            active
           {% endif %}
           "
           href="?status=dropped"
        >
          Брошено
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link
           {% if status == 'cancelled' %}
            active
           {% endif %}
           "
           href="?status=cancelled"
        >
          Отменено
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link
           {% if not status %}
            active
           {% endif %}
           "
           href="{% url 'tasks:main_page' %}"
        >
          <b>Все таски</b>
        </a>
      </li>
    </ul>
  </div>
</nav>
<div class="container mt-4">
  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for task in tasks %}
      {% include 'includes/task.html' %}
    {% endfor %}
  </div>
</div>
{% endblock body %}

task_manager/templates/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block body %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            {% if form.errors %}
              {% for error in field.errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

task_manager/templates/main_page.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Ваши таски{% endblock title %}
{% block body %}
<nav class="navbar navbar-light" style="font-weight:bold; margin-top: 24px">
  <div class="container">
    <ul class="nav nav-pills">
      <li class="nav-item">
        <a class="nav-link
           {% if status == 'in_progress' %}
            active
           {% endif %}
           "
           href="?status=in_progress"
        >
            Активные
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link
           {% if status == 'postponed' %}
            active
           {% endif %}
           "
           href="?status=postponed"
        >
          Отложено
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link
           {% if status == 'completed' %}
            active
           {% endif %}
           "
           href="?status=completed"
        >
          Выполнено
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link
           {% if status == 'dropped' %}
            active
           {% endif %}
           "
           href="?status=dropped"
        >
          Брошено
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link
           {% if status == 'cancelled' %}
            active
           {% endif %}
           "
           href="?status=cancelled"
        >
          Отменено
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link
           {% if not status %}
            active
           {% endif %}
           "
           href="{% url 'tasks:main_page' %}"
        >
          <b>Все таски</b>
        </a>
      </li>
    </ul>
  </div>
</nav>
<div class="container mt-4">
  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for task in tasks %}
      {% include 'includes/task.html' %}
    {% endfor %}
  </div>
</div>
{% endblock body %}

task_manager/templates/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block body %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Зарегистрироваться
        </div>
        <div class="card-body">
          {% load user_filters %}
          {% if form.errors %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}
            <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {% for field in form %}
              {% if form.errors %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endif %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|linebreaksbr }}
                  </small>
                {% endif %}
              </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}

task_manager/templates/task_detail.html
{% extends "base.html" %}
{% load user_filters %}
{% block title %}Таска "{{ task }}"{% endblock title %}
{% block body %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-9">
            <div class="card shadow-sm border-0">
                <div class="card-body">
                    {% if not edit %}
                        <div class="row align-items-center">
                            <div class="mb-4 col-md-10" style="margin-top: 0px; margin-bottom: 12px !important; padding-left: 20px; padding-right: 0px">
                                <h2 class="card-title"><b>{{ task.name }}</b></h2>
                            </div>
                            {% if user == task.author %}
                                <div class="mb-4 col-md-2" style="padding-right: 16px; margin-top: 0px; margin-bottom: 12px !important;">
                                    <a href="?edit=true" class="btn btn-primary d-flex align-items-center justify-content-center">
                                        <span style="font-size: 16px">Редактировать</span>
                                    </a>
                                </div>
                            {% endif %}
                        </div>
                        {% if user == task.author %}
                            <form method="post">
                                {% csrf_token %}
                                <div class="row align-items-end">
                                    <style>
                                        select.form-control {
                                            text-align: center;      /* Для Chrome */
                                            text-align-last: center; /* Для Firefox */
                                            text-indent: 1px;        /* Костыль для Safari */
                                        }
                                    </style>
                                    <div class="mb-4 col-md-2">
                                        <label for="id_status" class="form-label fw-bold">Статус</label>
                                        {{ form.status|addclass:"form-control" }}
                                    </div>
                                    <div class="mb-4 col-md-2">
                                        <button type="submit" class="btn btn-primary" style="">Применить</button>
                                    </div>
                                </div>
                                <div style="display: none">
                                    {{ form.name }}
                                    {{ form.description }}
                                    {{ form.end_date }}
                                    {{ form.contributors }}
                                </div>
                            </form>
                        {% endif %}
                        <div class="mb-4">
                            <p style="font-size: 20px">{{ task.description|linebreaksbr }}</h5>
                        </div>
                    {% else %}
                        <form method="post">
                            {% csrf_token %}
                            <div class="row align-items-center">
                                <div class="mb-4 col-md-9">
                                    <h2 class="card-title">Редактирование</h2>
                                </div>
                                <div class="mb-4 col-md-3" style="padding-right: 16px">
                                    <a href="{% url 'tasks:task_detail' task.id %}" class="btn btn-primary d-flex align-items-center justify-content-center">
                                        <span style="font-size: 16px">Вернуться к этой таске</span>
                                    </a>
                                </div>
                            </div>
                            <div class="mb-4">
                                <label for="id_name" class="form-label fw-bold">Название таски</label>
                                {{ form.name|addclass:"form-control" }}
                            </div>
                            <div class="mb-4">
                                <label for="id_status" class="form-label fw-bold">Статус</label>
                                {{ form.status|addclass:"form-control" }}
                            </div>
                            <div class="mb-4">
                                <label for="id_description" class="form-label fw-bold">Описание таски</label>
                                {{ form.description|addclass:"form-control" }}
                            </div>
                            <div class="mb-4">
                                <label for="id_end_date" class="form-label fw-bold">Дата дедлайна</label>
                                {{ form.end_date|addclass:"form-control" }}
                            </div>
                            <div class="mb-4">
                                <label for="id_contributors" class="form-label fw-bold">
                                    Не делайте задачи в одиночку!
                                    Укажите через пробел юзернеймы тех,
                                    кто будет работать с вами над таской
                                </label>
                                {{ form.contributors|addclass:"form-control" }}
                            </div>
                            <button type="submit" class="btn btn-primary w-100">Применить изменения</button>
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>

        <!-- Дополнительная информация -->
        <div class="col-md-3">
            <div class="card shadow-sm border-0">
                <div class="card-body">
                    <h4 class="card-title mb-3">Детали таски</h4>
                    <ul class="list-group">
                        <li class="list-group-item border-0 ps-0">
                            <strong>Создана:</strong> {{ task.date }}
                        </li>
                        <li class="list-group-item border-0 ps-0">
                            <strong>Дедлайн:</strong> {{ task.end_date|default:"Нет. Главное не забей" }}
                        </li>
                        <li class="list-group-item border-0 ps-0">
                            <strong>Статус:</strong> {{ task.get_status_display }}
                        </li>
                        <li class="list-group-item border-0 ps-0">
                            <strong>Автор:</strong> {{ task.author.username }}
                        </li>
                        <li class="list-group-item border-0 ps-0">
                            <strong>Контрибьюторы:</strong>
                            {% if task.contributors.exists %}
                                {{ task.contributors.all|join:", " }}
                            {% else %}
                                Нет
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}